
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'yellow_taxi'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In dbt, the default materialization for a model is a view. This means, when you run 
# dbt run or dbt build, all of your models will be built as a view in your data platform. 
# The configuration below will override this setting for models in the example folder to 
# instead be materialized as tables. Any models you add to the root of the models folder will 
# continue to be built as views. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.


models:
  yellow_taxi:
    # Applies to all files under models/example/
    marts:
      payment:
        +materialized: table
        +tests:
          - not_null:
              severity: error
              error_if: ">=0.01"
    staging:
      +materialized: view
      +tests:
        - name: stg_yellow_taxi_agg
          tests:
            - unique:
                columns: ['trip_id']
                severity: error
                error_if: ">=0.01"
                                
            - not_null:
                columns: ['trip_id']
                severity: error
                error_if: ">=0.01"
                
        - not_null:
            severity: warn
            warn_if: ">=0.3"
            # error_if: ">0.5"
        - accepted_values:
            column_name: payment_type
            values: [1, 2, 3, 4, 5, 6]
            severity: error

    intermediate:
      +materialized: view
      +tests:
        - accepted_values:
            column_name: payment_type
            values: [1, 2, 3, 4, 5, 6]
            severity: error
        - not_null:
            severity: error
            error_if: ">=0.01"
        - unique:
            columns: ['trip_id']
            severity: error
            error_if: ">=0.01"